// 주요 주식 심볼 데이터베이스
export const stockSymbols = [
  // 미국 주요 기술주 (NASDAQ)
  {
    ticker: 'AAPL',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Apple Inc.',
    sector: 'Technology',
  },
  {
    ticker: 'MSFT',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Microsoft Corporation',
    sector: 'Technology',
  },
  {
    ticker: 'GOOGL',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Alphabet Inc. Class A',
    sector: 'Technology',
  },
  {
    ticker: 'GOOG',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Alphabet Inc. Class C',
    sector: 'Technology',
  },
  {
    ticker: 'AMZN',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Amazon.com Inc.',
    sector: 'Consumer Discretionary',
  },
  {
    ticker: 'TSLA',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Tesla Inc.',
    sector: 'Consumer Discretionary',
  },
  {
    ticker: 'META',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Meta Platforms Inc.',
    sector: 'Technology',
  },
  {
    ticker: 'NVDA',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'NVIDIA Corporation',
    sector: 'Technology',
  },
  {
    ticker: 'NFLX',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Netflix Inc.',
    sector: 'Communication Services',
  },
  {
    ticker: 'AMD',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Advanced Micro Devices Inc.',
    sector: 'Technology',
  },
  {
    ticker: 'INTC',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Intel Corporation',
    sector: 'Technology',
  },
  {
    ticker: 'PYPL',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'PayPal Holdings Inc.',
    sector: 'Financial Services',
  },
  {
    ticker: 'ADBE',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Adobe Inc.',
    sector: 'Technology',
  },
  {
    ticker: 'CRM',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Salesforce Inc.',
    sector: 'Technology',
  },
  {
    ticker: 'ORCL',
    exchange: 'NASDAQ',
    kind: 'STOCK',
    name: 'Oracle Corporation',
    sector: 'Technology',
  },

  // 미국 주요 기업 (NYSE)
  {
    ticker: 'JNJ',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Johnson & Johnson',
    sector: 'Healthcare',
  },
  {
    ticker: 'JPM',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'JPMorgan Chase & Co.',
    sector: 'Financial Services',
  },
  {
    ticker: 'V',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Visa Inc.',
    sector: 'Financial Services',
  },
  {
    ticker: 'PG',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Procter & Gamble Co.',
    sector: 'Consumer Staples',
  },
  {
    ticker: 'HD',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Home Depot Inc.',
    sector: 'Consumer Discretionary',
  },
  {
    ticker: 'MA',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Mastercard Inc.',
    sector: 'Financial Services',
  },
  {
    ticker: 'BAC',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Bank of America Corp.',
    sector: 'Financial Services',
  },
  {
    ticker: 'XOM',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Exxon Mobil Corporation',
    sector: 'Energy',
  },
  {
    ticker: 'WMT',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Walmart Inc.',
    sector: 'Consumer Staples',
  },
  {
    ticker: 'KO',
    exchange: 'NYSE',
    kind: 'STOCK',
    name: 'Coca-Cola Co.',
    sector: 'Consumer Staples',
  },

  // 한국 주요 주식 (KRX)
  {
    ticker: '005930',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '삼성전자',
    sector: 'Technology',
  },
  {
    ticker: '000660',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'SK하이닉스',
    sector: 'Technology',
  },
  {
    ticker: '035420',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'NAVER',
    sector: 'Technology',
  },
  {
    ticker: '035720',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '카카오',
    sector: 'Technology',
  },
  {
    ticker: '207940',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '삼성바이오로직스',
    sector: 'Healthcare',
  },
  {
    ticker: '006400',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '삼성SDI',
    sector: 'Technology',
  },
  {
    ticker: '051910',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'LG화학',
    sector: 'Materials',
  },
  {
    ticker: '068270',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '셀트리온',
    sector: 'Healthcare',
  },
  {
    ticker: '028260',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '삼성물산',
    sector: 'Industrials',
  },
  {
    ticker: '066570',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'LG전자',
    sector: 'Technology',
  },
  {
    ticker: '096770',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'SK이노베이션',
    sector: 'Energy',
  },
  {
    ticker: '003550',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'LG',
    sector: 'Industrials',
  },
  {
    ticker: '017670',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'SK텔레콤',
    sector: 'Communication Services',
  },
  {
    ticker: '030200',
    exchange: 'KRX',
    kind: 'STOCK',
    name: 'KT',
    sector: 'Communication Services',
  },
  {
    ticker: '032830',
    exchange: 'KRX',
    kind: 'STOCK',
    name: '삼성생명',
    sector: 'Financial Services',
  },

  // 주요 암호화폐
  {
    ticker: 'BTC',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Bitcoin',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'ETH',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Ethereum',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'BNB',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Binance Coin',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'ADA',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Cardano',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'DOT',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Polkadot',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'LINK',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Chainlink',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'UNI',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Uniswap',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'SOL',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Solana',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'MATIC',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Polygon',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'AVAX',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Avalanche',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'LUNA',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Terra Luna',
    sector: 'Cryptocurrency',
  },
  {
    ticker: 'ATOM',
    exchange: 'CRYPTO',
    kind: 'CRYPTO',
    name: 'Cosmos',
    sector: 'Cryptocurrency',
  },
];

// 심볼을 배치로 추가하는 함수
export function getSymbolBatches(batchSize: number = 10) {
  const batches = [];
  for (let i = 0; i < stockSymbols.length; i += batchSize) {
    batches.push(stockSymbols.slice(i, i + batchSize));
  }
  return batches;
}
